language: objective-c
osx_image: xcode7.3

env:
  global:
  # GITHUB USER
  - secure: "PJvFLVLLphYAKA3tVfD7vsTvNudHUjGVlzPFKaJBiAzMJK3lnKRWooDCfymxFSBrMQQ44/0qAe9e0KCPvJhsZPKC/VS4fBz0LyVArjoTrCFDbo3jowDc5IZrFJ3m0vBqg54okRbV81fEA5TAn/gPa3Ei8L/vqpN+0lnKwlpAmEHhVrr1o8n8zugXUtmZPzqPTU/i3a9aadRixKCVHKxOmIvfG+lm//EOWphTfyJ8CAfVW0BFmz4M6Szc3fZ60SbooHujCAwWUZjOSoVPy+qZC4L0FG3xy+23B4O5A1KyUSZZMNnefbDHdVGAVwNGYmCN2E5gOMjDIfRUmrlEAPxbYRY5W/yH7gMV4IritcbhaTaUgAB5p5H0Eq8cMNKbNx4ewAPeHfwWvPZVDhcqloCGvBpH4toOj8/7kTcwW1erZzZtgfI3QrR/7sYbCqA976hLh2tZe4TUx9uytLnjwDO95JNcwk7myH1GnqU8rFPP43+7uY4DIPlkwJPBS92jqX3qvAo5FcJJoNEaI52hJbN0dVtS0OPtGUzo+4pNb4qSxq9knG71IApEcoXGHrkCCAcOnaIm4gAY3+ST3sxb0AahPjGqxGARGknsd1CtqEymELoNFWlCr1AK79R2SHfVju5woRHf6hcEZi32113SmypoH76/gzYyZ8sY0kGlqz9w1H4="
  # GITHUB TOKEN
  secure: "iRb6OGoZCNrbQHq3tYJ+UAy6vwxfrmio7aKIrq8/cYr4k08OaJBxYpr0m98eIXma1N6c4a7Jp94wYWAfGuJkUQtcORfkrFHbMG+erX1kKrJhJkZ8CurBMmIQ5m1jABt7wPTwtxiWzsu8nqqmNFboGLL+cNP2n4/dq5zaobj/hUT/WIUiKziRwhILwNnChurzgZMFTnxKw6SNNdlrzJpRKAu/lXZvDFt/8tM90A5Pwll+Go8NaQGD2odM7Zl3os/WZaDYBEh7OemiKEiIbBLQEIxxg/9+GNe3WHV9jEJzu7zNbhy9OBVHyOXjL6sN3RtKerOlTDOQRjf+IBGTtkdz2OB6ayom+mR7fFxAe1V2ImeItfULkmnG3qh52eT/UoJcsoP39NzqvCt23GY4ifm1ld/jfuqwC/pDguOE7AGYC864ErXBFlTuUDacCJqWljlzHsyMLx5fkUrdDddBLm8MmjvJ7B9Fm6lWRj6hVQzw6pxoJB08HKcrlGEPQIjYkDxS5ushbH2JaLAQXpGbICWNL1BNRUIFPz2SyuxcUeDeK0APhPrwzVATzID8+ShGgsvRPGw/jaAmWf+UKBSA2eKjbGykdp4Mqeb7A1noqGGkM5qDOlEwx+IYIDLJZrNX6vyxkLSputiMlrMFAos0FbULqkhF1ZNMrANZQvdYK8o43Gs="

before_install:
  - brew update
  - brew install opam
  - opam init
  - opam switch 4.02.3
  - eval `opam config env`
  - opam update
before_script:
  - opam pin add -y reason-bin .
script:
  - ./release-binaries.sh
