language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew install opam
  - opam init
  - opam switch 4.02.3
  - eval `opam config env`
  - opam update
before_script:
  - opam pin add -y reason-bin .
script:
  - tree ~/.opam