language: cpp
matrix:
  include:
    - compiler: ": Linux, ocaml 4.03.0, opam 1.2.0"
      os: linux
      env: OCAML_VERSION=4.02.3 OPAM_VERSION=1.2.0

    - compiler: ": Mac, ocaml 4.03.0, opam 1.2.0"
      os: osx
      env: OCAML_VERSION=4.02.3 OPAM_VERSION=1.2.0

addons:
  apt:
    packages:
    - libelf-dev
    - aspcud

env:
  global:
  # GITHUB USER
  - secure: PJvFLVLLphYAKA3tVfD7vsTvNudHUjGVlzPFKaJBiAzMJK3lnKRWooDCfymxFSBrMQQ44/0qAe9e0KCPvJhsZPKC/VS4fBz0LyVArjoTrCFDbo3jowDc5IZrFJ3m0vBqg54okRbV81fEA5TAn/gPa3Ei8L/vqpN+0lnKwlpAmEHhVrr1o8n8zugXUtmZPzqPTU/i3a9aadRixKCVHKxOmIvfG+lm//EOWphTfyJ8CAfVW0BFmz4M6Szc3fZ60SbooHujCAwWUZjOSoVPy+qZC4L0FG3xy+23B4O5A1KyUSZZMNnefbDHdVGAVwNGYmCN2E5gOMjDIfRUmrlEAPxbYRY5W/yH7gMV4IritcbhaTaUgAB5p5H0Eq8cMNKbNx4ewAPeHfwWvPZVDhcqloCGvBpH4toOj8/7kTcwW1erZzZtgfI3QrR/7sYbCqA976hLh2tZe4TUx9uytLnjwDO95JNcwk7myH1GnqU8rFPP43+7uY4DIPlkwJPBS92jqX3qvAo5FcJJoNEaI52hJbN0dVtS0OPtGUzo+4pNb4qSxq9knG71IApEcoXGHrkCCAcOnaIm4gAY3+ST3sxb0AahPjGqxGARGknsd1CtqEymELoNFWlCr1AK79R2SHfVju5woRHf6hcEZi32113SmypoH76/gzYyZ8sY0kGlqz9w1H4=
  # GITHUB TOKEN
  - secure: GfH1Bklasoaap8zxYSH49/p87SgF6hP51ixVcvWmbkDXRcdg+mWYS0qDy4yhtcuS2hptddj41498P79t3SS0QFos6wirSJexQv6QPVy3UpZezdYzpVsPX8l4EjUXPS32+aX87Ar+xcomLdZ1gl0wDMHq5is892RrttJQoS1V4Iv+INm0bRVPnT52oIPExvbkMkicJa//wn0kmejSW/msW3KdDITpKfKgmQ2f3NqJWug4zDs8iMBGgNFnQusb37K1rXdW7dFL73xmqVARGpxu9ToJ46Yzc9CeVYBAy+x7kUWKyvgO0StwcKav+8PRuEfNdj0Wjfm4Shq5z72l1GmvO0rL7Doep+Erudou53/W3XnFhsEl1EIhOWP3di8f21iWo0H39EzguZeY0XF9JAgXos9lVfhA9a1dFugFADyv79umyZMnSHALROoZdBNftWYBlDP1z/uo1MXPD4S6vFpz/J1URFxkOtwOiv5TCAq8Z8VwEidkWDZfvDuxIAi0cExPHcWsP6eA+HCWoYZi0CfN/AmZdmH135J6Uiiz8kUDASaHGgbwizxRTI3XFt1WbENhRCj3Nq7LQgD+GriOaJlhmolf5dNZSdZVqY9Iagw+raiaC4WHPRxIBKJqJgqX72tQXNnZo9fxhIYTK8eU7dzyCLlsXLw5EFqegPFqyiJ7rUs=

before_install: bash -e resources/travis/before_install.sh

before_script:
  - opam pin add -y reason-bin .
script:
  - bash -e ./release-binaries.sh
